### ISSUE TITLE
链接文章没了

### ISSUE THREAD

**Issue by mkitto** [Lafree317/Unity-InterviewQuestion#1]
https://github.com/Lafree317/Unity-InterviewQuestion/blob/master/UnityEngine.md#10000%E4%B8%AAmonobehavior%E6%AF%8F%E4%B8%AA%E5%90%84%E8%87%AA%E6%89%A7%E8%A1%8Cupdate%E5%92%8C%E6%94%BE%E5%88%B0%E4%B8%80%E4%B8%AAupdate%E9%87%8C%E6%89%A7%E8%A1%8C%E5%93%AA%E4%B8%AA%E6%95%88%E7%8E%87%E6%9B%B4%E9%AB%98%E4%B8%BA%E4%BB%80%E4%B9%88

**Comment by jsaon-L** [comment]
建议引用这个unity官方博客 https://blog.unity.com/engine-platform/10000-update-calls

**Comment by Lafree317** [comment]
谢谢，已经修改
